# DSPy RAG Agent Configuration - Optimized Version
# This file contains optimized configurations for production use with compiled DSPy programs
# Use this config when you have a trained/optimized DSPy program available

# LLM Configuration - Optimized for performance
llm_config:
  endpoint: "databricks/databricks-claude-3-7-sonnet"
  max_tokens: 1500  # Reduced for faster response times
  temperature: 0.0  # More deterministic responses
  top_p: 0.9  # Slightly more focused sampling

# Vector Search Configuration - Optimized retrieval
vector_search:
  index_fullname: null  # Will be set via environment variable VS_INDEX_FULLNAME
  text_column_name: "chunk"
  docs_id_column_name: "id"
  columns: ["id", "title", "chunk_id"]
  top_k: 3  # Reduced for faster retrieval and more focused context

# DSPy Configuration - Points to optimized program
dspy_config:
  response_generator_signature: "context, request -> response"
  optimized_program_path: "/tmp/optimized_dspy_program.pkl"  # Path to your optimized program
  
# Agent Configuration - Optimized for production
agent_config:
  use_optimized: true  # Always use optimized program
  enable_tracing: false  # Disabled for performance in production
  verbose: false  # Reduced logging for production
  max_iterations: 5  # Reduced for faster response times

# MLflow Configuration - Production settings
mlflow_config:
  enable_autolog: false  # Disabled for performance in production
  experiment_name: "dspy-rag-agent-optimized"
  registered_model_name: "dspy_rag_chat_agent_optimized"

# Performance Optimizations
performance_config:
  # Caching settings
  enable_response_caching: true
  cache_ttl_seconds: 3600  # 1 hour cache
  
  # Batch processing settings
  batch_size: 16
  max_concurrent_requests: 10
  
  # Memory optimization
  enable_memory_optimization: true
  gc_threshold: 1000  # Garbage collection threshold

# Environment Variables (for documentation)
# These should be set in your production environment:
# - VS_INDEX_FULLNAME: catalog.schema.index_name (Unity Catalog path)
# - DSPY_LLM_ENDPOINT: Override LLM endpoint if needed
# - DSPY_TOP_K: Override top_k for retrieval if needed (recommended: 3)
# - DSPY_OPTIMIZED_PROGRAM_PATH: Path to optimized program (required for this config) 