# DSPy RAG Agent Configuration
# This file contains all parameterized configurations for the agent, 
# vector search, and LLM settings

# LLM Configuration
llm_config:
  endpoint: "databricks/databricks-claude-3-7-sonnet"
  max_tokens: 2500
  temperature: 0.01
  top_p: 0.95

# Vector Search Configuration
vector_search:
  index_fullname: users.alex_miller.wikipedia_chunks_index  # or can be set via environment variable VS_INDEX_FULLNAME
  text_column_name: "chunk"
  docs_id_column_name: "id"
  columns: ["id", "title", "chunk_id"]
  top_k: 5

# DSPy Configuration
dspy_config:
  response_generator_signature: "context, request -> response"
  optimized_program_path: null  # Will be set via environment variable DSPY_OPTIMIZED_PROGRAM_PATH
  
# Agent Configuration
agent_config:
  use_optimized: true
  enable_tracing: true
  verbose: true
  max_iterations: 10

# MLflow Configuration
mlflow_config:
  enable_autolog: true
  experiment_name: "dspy-rag-agent"
  registered_model_name: "dspy_rag_chat_agent"

# Environment Variables (for documentation)
# These should be set in your environment:
# - VS_INDEX_FULLNAME: catalog.schema.index_name (Unity Catalog path)
# - DSPY_LLM_ENDPOINT: Override LLM endpoint if needed
# - DSPY_TOP_K: Override top_k for retrieval if needed
# - DSPY_OPTIMIZED_PROGRAM_PATH: Path to optimized program if available 